### ISSUE TITLE
Add npm Repository

### ISSUE THREAD

**Issue by anonyco** [frqnck/apt.js#4]
npm is the hot old way that libraries can be easily managed when building a website

**Comment by frqnck** [comment]
Hey @anonyco. This library is listed [on npm under apt.js](https://www.npmjs.com/package/apt.js). It is not too obvious I guess. This should be mentioned at the top of the README rather than the bottom, I will remedy this... I haven't gave this package much love -- please feel free to contribute. Thanks.

**Comment by anonyco** [comment]
Yikes! I didn't even see that. Yes, you should make that more obvious by having a Bash snippet like so.

    npm install apt.js
